
// Generated by dojo-bindgen on Fri, 23 Aug 2024 20:00:11 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;



// Type definition for `dojo::model::layout::Layout` enum
export type Layout = { type: 'Fixed'; value: RecsType.NumberArray; } | { type: 'Struct'; value: RecsType.StringArray; } | { type: 'Tuple'; value: RecsType.StringArray; } | { type: 'Array'; value: RecsType.StringArray; } | { type: 'ByteArray'; } | { type: 'Enum'; value: RecsType.StringArray; };

export const LayoutDefinition = {
    type: RecsType.String,
    value: RecsType.String
};
        
// Type definition for `octoguns::models::character::Camera` struct
export interface Camera {
    entity_id: Number;
    pitch: Number;
    yaw: Number;
    roll: Number;
    
}
export const CameraDefinition = {
    entity_id: RecsType.Number,
    pitch: RecsType.Number,
    yaw: RecsType.Number,
    roll: RecsType.Number,
    
};

// Type definition for `dojo::model::layout::FieldLayout` struct
export interface FieldLayout {
    selector: BigInt;
    layout: Layout;
    
}
export const FieldLayoutDefinition = {
    selector: RecsType.BigInt,
    layout: LayoutDefinition,
    
};

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: String[];
    pending_word: BigInt;
    pending_word_len: Number;
    
}
export const ByteArrayDefinition = {
    data: RecsType.StringArray,
    pending_word: RecsType.BigInt,
    pending_word_len: RecsType.Number,
    
};


// Type definition for `octoguns::models::character::Character` struct
export interface Character {
    entity_id: Number;
    session_id: Number;
    player_id: Number;
    steps_amount: Number;
    
}
export const CharacterDefinition = {
    entity_id: RecsType.Number,
    session_id: RecsType.Number,
    player_id: RecsType.Number,
    steps_amount: RecsType.Number,
    
};


// Type definition for `octoguns::models::character::Health` struct
export interface Health {
    entity_id: Number;
    health: Number;
    
}
export const HealthDefinition = {
    entity_id: RecsType.Number,
    health: RecsType.Number,
    
};


// Type definition for `octoguns::models::map::Map` struct
export interface Map {
    map_id: Number;
    map_objects_id: Number[];
    
}
export const MapDefinition = {
    map_id: RecsType.Number,
    map_objects_id: RecsType.NumberArray,
    
};


// Type definition for `octoguns::models::map::Vec3` struct
export interface Vec3 {
    x: Number;
    y: Number;
    z: Number;
    
}
export const Vec3Definition = {
    x: RecsType.Number,
    y: RecsType.Number,
    z: RecsType.Number,
    
};

// Type definition for `octoguns::models::map::MapObjects` struct
export interface MapObjects {
    map_object_id: Number;
    dimensions: Vec3;
    coords: Vec3;
    
}
export const MapObjectsDefinition = {
    map_object_id: RecsType.Number,
    dimensions: Vec3Definition,
    coords: Vec3Definition,
    
};


// Type definition for `octoguns::models::sessions::Session` struct
export interface Session {
    session_id: Number;
    player1: BigInt;
    player2: BigInt;
    map_id: Number;
    state: Number;
    
}
export const SessionDefinition = {
    session_id: RecsType.Number,
    player1: RecsType.BigInt,
    player2: RecsType.BigInt,
    map_id: RecsType.Number,
    state: RecsType.Number,
    
};


// Type definition for `octoguns::models::character::Position` struct
export interface Position {
    entity_id: Number;
    x: Number;
    y: Number;
    z: Number;
    
}
export const PositionDefinition = {
    entity_id: RecsType.Number,
    x: RecsType.Number,
    y: RecsType.Number,
    z: RecsType.Number,
    
};


export function defineContractComponents(world: World) {
    return {

        // Model definition for `octoguns::models::character::Camera` model
        Camera: (() => {
            return defineComponent(
                world,
                {
                    entity_id: RecsType.Number,
                    pitch: RecsType.Number,
                    yaw: RecsType.Number,
                    roll: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "Camera",
                        types: ["u32", "u8", "u8", "u8"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `octoguns::models::character::Character` model
        Character: (() => {
            return defineComponent(
                world,
                {
                    entity_id: RecsType.Number,
                    session_id: RecsType.Number,
                    player_id: RecsType.Number,
                    steps_amount: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "Character",
                        types: ["u32", "u32", "u8", "u32"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `octoguns::models::character::Health` model
        Health: (() => {
            return defineComponent(
                world,
                {
                    entity_id: RecsType.Number,
                    health: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "Health",
                        types: ["u32", "u8"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `octoguns::models::map::Map` model
        Map: (() => {
            return defineComponent(
                world,
                {
                    map_id: RecsType.Number,
                    map_objects_id: RecsType.NumberArray,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "Map",
                        types: ["u32", "array"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `octoguns::models::map::MapObjects` model
        MapObjects: (() => {
            return defineComponent(
                world,
                {
                    map_object_id: RecsType.Number,
                    dimensions: Vec3Definition,
                    coords: Vec3Definition,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "MapObjects",
                        types: ["u32"],
                        customTypes: ["Vec3", "Vec3"],
                    },
                }
            );
        })(),

        // Model definition for `octoguns::models::sessions::Session` model
        Session: (() => {
            return defineComponent(
                world,
                {
                    session_id: RecsType.Number,
                    player1: RecsType.BigInt,
                    player2: RecsType.BigInt,
                    map_id: RecsType.Number,
                    state: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "Session",
                        types: ["u32", "ContractAddress", "ContractAddress", "u32", "u8"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `octoguns::models::character::Position` model
        Position: (() => {
            return defineComponent(
                world,
                {
                    entity_id: RecsType.Number,
                    x: RecsType.Number,
                    y: RecsType.Number,
                    z: RecsType.Number,
                },
                {
                    metadata: {
                        namespace: "octoguns",
                        name: "Position",
                        types: ["u32", "u16", "u16", "u16"],
                        customTypes: [],
                    },
                }
            );
        })(),
    };
}
